export const LOAD_PLAYERS_SUCCESS = "LOAD_PLAYERS_SUCCESS";
export const LOAD_COACHES_SUCCESS = "LOAD_COACHES_SUCCESS";
export const CREATE_PLAYER_SUCCESS = "CREATE_PLAYER_SUCCESS";
export const UPDATE_PLAYER_SUCCESS = "UPDATE_PLAYER_SUCCESS";
export const BEGIN_API_CALL = "BEGIN_API_CALL";
